<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: EventType.proto

namespace PaulhenriL\APMEvents;

use UnexpectedValueException;

/**
 * Protobuf type <code>PaulhenriL.APMEvents.EventType</code>
 */
class EventType
{
    /**
     * Generated from protobuf enum <code>request = 0;</code>
     */
    const request = 0;

    private static $valueToName = [
        self::request => 'request',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

