<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Request.proto

namespace PaulhenriL\APMEvents;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>PaulhenriL.APMEvents.Request</code>
 */
class Request extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string type = 1;</code>
     */
    protected $type = '';
    /**
     * Generated from protobuf field <code>string timestamp = 2;</code>
     */
    protected $timestamp = '';
    /**
     * Generated from protobuf field <code>string url = 3;</code>
     */
    protected $url = '';
    /**
     * Generated from protobuf field <code>string path = 4;</code>
     */
    protected $path = '';
    /**
     * Generated from protobuf field <code>string method = 5;</code>
     */
    protected $method = '';
    /**
     * Generated from protobuf field <code>uint32 status = 6;</code>
     */
    protected $status = 0;
    /**
     * Generated from protobuf field <code>string servername = 7;</code>
     */
    protected $servername = '';
    /**
     * Generated from protobuf field <code>float duration = 8;</code>
     */
    protected $duration = 0.0;
    /**
     * Generated from protobuf field <code>string memory_peak_usage = 9;</code>
     */
    protected $memory_peak_usage = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $type
     *     @type string $timestamp
     *     @type string $url
     *     @type string $path
     *     @type string $method
     *     @type int $status
     *     @type string $servername
     *     @type float $duration
     *     @type string $memory_peak_usage
     * }
     */
    public function __construct($data = NULL) {
        \PaulhenriL\APMEvents\Metadata\Request::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string type = 1;</code>
     * @return string
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Generated from protobuf field <code>string type = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkString($var, True);
        $this->type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string timestamp = 2;</code>
     * @return string
     */
    public function getTimestamp()
    {
        return $this->timestamp;
    }

    /**
     * Generated from protobuf field <code>string timestamp = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setTimestamp($var)
    {
        GPBUtil::checkString($var, True);
        $this->timestamp = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string url = 3;</code>
     * @return string
     */
    public function getUrl()
    {
        return $this->url;
    }

    /**
     * Generated from protobuf field <code>string url = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->url = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string path = 4;</code>
     * @return string
     */
    public function getPath()
    {
        return $this->path;
    }

    /**
     * Generated from protobuf field <code>string path = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setPath($var)
    {
        GPBUtil::checkString($var, True);
        $this->path = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string method = 5;</code>
     * @return string
     */
    public function getMethod()
    {
        return $this->method;
    }

    /**
     * Generated from protobuf field <code>string method = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setMethod($var)
    {
        GPBUtil::checkString($var, True);
        $this->method = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 status = 6;</code>
     * @return int
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>uint32 status = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkUint32($var);
        $this->status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string servername = 7;</code>
     * @return string
     */
    public function getServername()
    {
        return $this->servername;
    }

    /**
     * Generated from protobuf field <code>string servername = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setServername($var)
    {
        GPBUtil::checkString($var, True);
        $this->servername = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float duration = 8;</code>
     * @return float
     */
    public function getDuration()
    {
        return $this->duration;
    }

    /**
     * Generated from protobuf field <code>float duration = 8;</code>
     * @param float $var
     * @return $this
     */
    public function setDuration($var)
    {
        GPBUtil::checkFloat($var);
        $this->duration = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string memory_peak_usage = 9;</code>
     * @return string
     */
    public function getMemoryPeakUsage()
    {
        return $this->memory_peak_usage;
    }

    /**
     * Generated from protobuf field <code>string memory_peak_usage = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setMemoryPeakUsage($var)
    {
        GPBUtil::checkString($var, True);
        $this->memory_peak_usage = $var;

        return $this;
    }

}

