<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: EventType.proto

namespace PaulhenriL\APMEvents\Metadata;

class EventType
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a6b0a0f4576656e74547970652e70726f746f12145061756c68656e72694c2e41504d4576656e74732a180a094576656e7454797065120b0a077265717565737410004220e2021d5061756c68656e72694c5c41504d4576656e74735c4d65746164617461620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

