<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Request.proto

namespace PaulhenriL\APMEvents\Metadata;

class Request
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0af8010a0d526571756573742e70726f746f12145061756c68656e72694c2e41504d4576656e747322a6010a0752657175657374120c0a047479706518012001280912110a0974696d657374616d70180220012809120b0a0375726c180320012809120c0a0470617468180420012809120e0a066d6574686f64180520012809120e0a0673746174757318062001280d12120a0a7365727665726e616d6518072001280912100a086475726174696f6e18082001280212190a116d656d6f72795f7065616b5f75736167651809200128094220e2021d5061756c68656e72694c5c41504d4576656e74735c4d65746164617461620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

