<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ViewRender.proto

namespace PaulhenriL\APMEvents\Metadata;

class ViewRender
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0aac010a105669657752656e6465722e70726f746f12145061756c68656e72694c2e41504d4576656e747322580a0a5669657752656e646572120a0a02696418012001280912100a0862617463685f6964180220012809120c0a046e616d65180320012809120c0a047061746818042001280912100a086475726174696f6e18052001280d4220e2021d5061756c68656e72694c5c41504d4576656e74735c4d65746164617461620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

