<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ViewRendering.proto

namespace PaulhenriL\APMEvents\Metadata;

class ViewRendering
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a81010a135669657752656e646572696e672e70726f746f12145061756c68656e72694c2e41504d4576656e7473222a0a0a5669657752656e646572120a0a02696418012001280912100a0862617463685f69641802200128094220e2021d5061756c68656e72694c5c41504d4576656e74735c4d65746164617461620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

